name: Galaxio Docker Images Building

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-repo galaxioteam/base-cache --cache-copy-layers=true --cache-ttl=24h"

jobs:
  base-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            galaxioteam/base:latest
            galaxioteam/base:${{ github.ref_name }}
          cache-from: type=registry,ref=galaxioteam/base-cache:cache
          cache-to: type=registry,ref=galaxioteam/base-cache:cache,mode=max
  java-build:
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: base-build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Java ${{ matrix.java-version }} and Push Image to docker registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./java.Dockerfile
          push: true
          tags: |
            galaxioteam/base-jdk:latest
            galaxioteam/base-jdk:${{ github.ref_name }}
          cache-from: type=registry,ref=galaxioteam/base-cache:cache
          cache-to: type=registry,ref=galaxioteam/base-cache:cache,mode=max
          build-args: |
            BASE_VERSION=${{ github.ref_name }}
            JAVA_VERSION=${{ matrix.java-version }}
