name: Galaxio Docker Images Building

on:
  pull_request:
    branches: [ '**' ]
  push:
    tags: [ v* ]

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  build-test:
    runs-on: ubuntu-22.04
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug
    permissions:
      contents: read # read the repository
    steps:
      - name: Test Build with kaniko
        run: |
          /kaniko/executor --dockerfile="Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.head_ref }}" \
            --no-push
#            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
        #            --destination="$DOCKER_IMAGE_NAME:$(echo ${GITHUB_SHA} | head  -c 7)" \
        #            ${{ env.KANIKO_CACHE_ARGS }} \

#        env:
#          GIT_USERNAME: ${{ github.actor }}
#          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#          DOCKER_IMAGE_NAME: "<docker-username>/nginx"
