name: Galaxio Docker Images Building

on:
  push:
    branches:
      - main
    tags: [ * ]

jobs:
  test-build:
    runs-on: ubuntu-22.04
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug
    permissions:
      contents: read # read the repository
    steps:
      - name: Test Build with kaniko
        run: |
          /kaniko/executor --dockerfile="Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.head_ref }}" \
            --no-push
