name: Galaxio Docker Images Building

on:
  workflow_dispatch:
  pull_request:
    branches: [ '**' ]

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-repo galaxioteam/base-cache --cache-copy-layers=true --cache-ttl=24h"

jobs:
  base-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            galaxioteam/base:latest
            galaxioteam/base:${GITHUB_SHA}
          cache-from: type=registry,ref=galaxioteam/base-cache:cache
          cache-to: type=registry,ref=galaxioteam/base-cache:cache,mode=max
  java-build:
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    runs-on: ubuntu-22.04
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug
    needs: base-build
    permissions:
      contents: read # read the repository
    steps:
      - name: Build Java ${{ matrix.java-version }} and Push Image to docker registry
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "$(echo -n "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" | base64 )"
              }
            }
          }
          EOF
          
          export IFS=''
          /kaniko/executor --dockerfile="java.Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.head_ref }}" \
            --build-arg "BASE_VERSION=${GITHUB_SHA}" \
            --build-arg "JAVA_VERSION=${{ matrix.java-version }}" \
            --cleanup \
            --destination="$DOCKER_IMAGE_NAME:${{ matrix.java-version }}-${GITHUB_SHA}" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --push-retry 5
        env:
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE_NAME: "galaxioteam/base-jdk"
